/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
    }
    interface MyMidSubcomponent {
    }
    interface MySubcomponent {
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLMyMidSubcomponentElement extends Components.MyMidSubcomponent, HTMLStencilElement {
    }
    var HTMLMyMidSubcomponentElement: {
        prototype: HTMLMyMidSubcomponentElement;
        new (): HTMLMyMidSubcomponentElement;
    };
    interface HTMLMySubcomponentElement extends Components.MySubcomponent, HTMLStencilElement {
    }
    var HTMLMySubcomponentElement: {
        prototype: HTMLMySubcomponentElement;
        new (): HTMLMySubcomponentElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "my-mid-subcomponent": HTMLMyMidSubcomponentElement;
        "my-subcomponent": HTMLMySubcomponentElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
    }
    interface MyMidSubcomponent {
    }
    interface MySubcomponent {
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "my-mid-subcomponent": MyMidSubcomponent;
        "my-subcomponent": MySubcomponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "my-mid-subcomponent": LocalJSX.MyMidSubcomponent & JSXBase.HTMLAttributes<HTMLMyMidSubcomponentElement>;
            "my-subcomponent": LocalJSX.MySubcomponent & JSXBase.HTMLAttributes<HTMLMySubcomponentElement>;
        }
    }
}
